spring:
  version: @project.version@
  application:
    name: @project.artifactId@
    des: "Controller of Sonic Cloud Real Machine Platform"
  profiles:
    active: @project.artifactId@,eureka,actuator,jdbc,feign,logging,knife4j,user