spring:
  version: @project.version@
  application:
    name: @project.artifactId@
    des: "Gateway of Sonic Cloud Real Machine Platform"
  profiles:
    active: @project.artifactId@,actuator,eureka,logging,user
